services:
  microservice:
    container_name: microservice
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: "${VERSION}"
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - APP_PORT=${APP_PORT}
      - APP_ENV=${APP_ENV}
      - TRACE_ENDPOINT=jaeger:4318
    networks:
      - microservice-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "./healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

networks:
  microservice-net:
    name: microservice-network
    driver: bridge
