services:
  user-service:
    container_name: user-service
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: "${VERSION}"
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - APP_ENV=${APP_ENV}
      - APP_PORT=${APP_PORT}
    networks:
      - microservice-net
    restart: unless-stopped

networks:
  microservice-net:
    name: microservice-network
    driver: bridge
