services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - microservice-prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - microservice-net
    restart: unless-stopped

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    volumes:
      - microservice-grafana-data:/var/lib/grafana
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3001:3000"
    networks:
      - microservice-net
    restart: unless-stopped

  couchbase:
    container_name: couchbase
    image: couchbase/server:7.2.0
    ports:
      - "8091-8094:8091-8094"
      - "11210:11210"
    volumes:
      - microservice-couchbase-data:/opt/couchbase/var
    networks:
      - microservice-net
    restart: unless-stopped

networks:
  microservice-net:
    name: microservice-network
    external: true

volumes:
  microservice-grafana-data:
    name: microservice-grafana-data
  microservice-prometheus-data:
    name: microservice-prometheus-data
  microservice-couchbase-data:
    name: microservice-couchbase-data
