app:
  name: "User-Service"

server:
  read_timeout: "5s"
  write_timeout: "10s"
  idle_timeout: "120s"

logger:
  level: "debug"

database:
  driver: "memory"
  host: "couchbase"
  bucket: "default"
  username: "Administrator"
  password: "123456"
