app:
  name: "Microservice"
  port: "3000"
  env: "production"

server:
  read_timeout: "5s"
  write_timeout: "10s"
  idle_timeout: "120s"

logger:
  level: "info"

database:
  driver: "couchbase"
  host: "couchbase"
  bucket: "microservice-bucket"
  username: "admin"
  password: "Admin123."

trace:
  exporter: "jaeger"
  endpoint: "http://jaeger:4318"
