app:
  name: "Microservice"
  port: "3001"
  env: "test"

server:
  read_timeout: "5s"
  write_timeout: "10s"
  idle_timeout: "120s"

logger:
  level: "error"

database:
  driver: "memory"
  host: ""
  bucket: ""
  username: ""
  password: ""

trace:
  exporter: "noop"
  endpoint: ""
